GET http://localhost:3000/to-do-items

###

POST http://localhost:3000/to-do-items
Content-Type: application/json

{
  "label": "Test"
}

###

PATCH http://localhost:3000/to-do-items/5dc5844b667a8d36400867d2
Content-Type: application/json

{
  "label": "Test2"
}

###

PATCH http://localhost:3000/to-do-items/5dc5844b667a8d36400867d2
Content-Type: application/json

{
  "isDone": true
}


###

DELETE http://localhost:3000/to-do-items/5dc5844b667a8d36400867d2
